#(c) savagerebirth.com 2011
#imports
import logging;
from silverback import *;
import tools;
import vectors;
from vectors import Vec3; # ya I know, but this fixes namespace problems for servers

def event_frame():
	gblEventHandler.runQueue()

#globals and constants go here

#server stati
GAME_STATUS_EMPTY=0;
GAME_STATUS_SETUP=1;
GAME_STATUS_WARMUP=2;   #warming up
GAME_STATUS_NORMAL=3;   #normal play mode
GAME_STATUS_ENDED=4;    #game finished and stats screen is shown
GAME_STATUS_NEXTMAP=5;  #about to go to the next map
GAME_STATUS_PLAYERCHOSENMAP=6;  #about to go to a map that was voted in or that the referee chose
GAME_STATUS_RANDOMMAP=7;
GAME_STATUS_RESTARTING=8;

#player stati
PLAYER_STATUS_LOBBY=0;
PLAYER_STATUS_UNITSELECT=1; #loadout
PLAYER_STATUS_SPAWNPOINT_SELECT=2;
PLAYER_STATUS_COMMANDER=3;
PLAYER_STATUS_PLAYER=4;
PLAYER_STATUS_SPECTATE=5;
PLAYER_STATUS_ENDGAME=6;
PLAYER_STATUS_SHOPPING=7; #this was added to support MOBA-like shopping mode

#cvar flags   ex: flags = (CVAR_SAVECONFIG|CVAR_VALUERANGE)
CVAR_SAVECONFIG =1;
CVAR_READONLY   =4;
CVAR_WORLDCONFIG=512;
CVAR_CHEAT      =1024;
CVAR_TRANSMIT   =2048;
CVAR_VALUERANGE =8192;
CVAR_SERVERINFO =16384;

#gametypes
GAMETYPE_RTSS       =0;
GAMETYPE_DEATHMATCH =1;
GAMETYPE_DUEL       =2;
GAMETYPE_CTF        =3;

#dueling states
DP_NOTDUELING    =0;
DP_READY         =1;
DP_DUELING       =2;
DP_CHALLENGING   =3;

#damage flags
DAMAGE_NO_KNOCKBACK = 0x00000001
DAMAGE_NO_AIR_TARGETS       = 0x00000002
DAMAGE_NO_GROUND_TARGETS    = 0x00000004
DAMAGE_UNBLOCKABLE  = 0x00000008
DAMAGE_SELF_NONE    = 0x00000010
DAMAGE_SELF_HALF    = 0x00000020
DAMAGE_NO_FALLOFF   = 0x00000040
DAMAGE_NO_STRUCTURES= 0x00000080
DAMAGE_QUAKE_EVENT  = 0x00000100
DAMAGE_NO_REACTION  = 0x00000200
DAMAGE_STRIP_STATES = 0x00000400
DAMAGE_EXPLOSIVE    = 0x00000800
#DAMAGE_PHYSICAL    = 0x00001000
#DAMAGE_MAGICAL     = 0x00002000
DAMAGE_SPLASH       = 0x00004000
DAMAGE_FALL         = 0x00008000
DAMAGE_SILENT       = 0x00010000
DAMAGE_DELAYED      = 0x00020000

AnimStates = tools.enum(
'AS_IDLE',

'AS_MELEE_1',
'AS_MELEE_2',
'AS_MELEE_3',
'AS_MELEE_4',
'AS_ALT_MELEE_1',
'AS_ALT_MELEE_2',
'AS_ALT_MELEE_3',
'AS_ALT_MELEE_4',
'AS_MELEE_CHARGE',
'AS_MELEE_RELEASE',

'AS_MELEE_MOVE_1',
'AS_MELEE_MOVE_2',
'AS_MELEE_MOVE_3',
'AS_MELEE_MOVE_4',
'AS_MELEE_MOVE_CHARGE',
'AS_MELEE_MOVE_RELEASE',

'AS_BLOCK',

'AS_WALK_LEFT',
'AS_WALK_RIGHT',
'AS_WALK_FWD',
'AS_WALK_BACK',

'AS_RUN_LEFT',
'AS_RUN_RIGHT',
'AS_RUN_FWD',
'AS_RUN_BACK',

'AS_SPRINT_LEFT',
'AS_SPRINT_RIGHT',
'AS_SPRINT_FWD',
'AS_SPRINT_BACK',

'AS_JUMP_START_LEFT',
'AS_JUMP_START_RIGHT',
'AS_JUMP_START_FWD',
'AS_JUMP_START_BACK',

'AS_JUMP_MID_LEFT',
'AS_JUMP_MID_RIGHT',
'AS_JUMP_MID_FWD',
'AS_JUMP_MID_BACK',

'AS_JUMP_END_LEFT',
'AS_JUMP_END_RIGHT',
'AS_JUMP_END_FWD',
'AS_JUMP_END_BACK',

'AS_JUMP_UP_START',
'AS_JUMP_UP_MID',
'AS_JUMP_UP_END',

'AS_JUMP_LAND',

'AS_DODGE_START_LEFT',
'AS_DODGE_START_RIGHT',
'AS_DODGE_START_FWD',
'AS_DODGE_START_BACK',

'AS_DODGE_MID_LEFT',
'AS_DODGE_MID_RIGHT',
'AS_DODGE_MID_FWD',
'AS_DODGE_MID_BACK',

'AS_DODGE_END_LEFT',
'AS_DODGE_END_RIGHT',
'AS_DODGE_END_FWD',
'AS_DODGE_END_BACK',

'AS_CROUCH_IDLE',

'AS_CROUCH_LEFT',
'AS_CROUCH_RIGHT',
'AS_CROUCH_FWD',
'AS_CROUCH_BACK',

'AS_WALK_WITH_BAG',

'AS_MINE',
'AS_REPAIR',
'AS_CONSTRUCT',

'AS_WOUNDED_LEFT',
'AS_WOUNDED_RIGHT',
'AS_WOUNDED_FWD',
'AS_WOUNDED_BACK',

'AS_DEATH_GENERIC',
'AS_DEATH_LEFT',
'AS_DEATH_RIGHT',
'AS_DEATH_FWD',
'AS_DEATH_BACK',

'AS_RESURRECTED',

'AS_WEAPON_IDLE_1',
'AS_WEAPON_IDLE_2',
'AS_WEAPON_IDLE_3',
'AS_WEAPON_IDLE_4',
'AS_WEAPON_IDLE_5',
'AS_WEAPON_IDLE_6',

'AS_WEAPON_CHARGE_1',
'AS_WEAPON_CHARGE_2',
'AS_WEAPON_CHARGE_3',
'AS_WEAPON_CHARGE_4',
'AS_WEAPON_CHARGE_5',
'AS_WEAPON_CHARGE_6',

'AS_WEAPON_FIRE_1',
'AS_WEAPON_FIRE_2',
'AS_WEAPON_FIRE_3',
'AS_WEAPON_FIRE_4',
'AS_WEAPON_FIRE_5',
'AS_WEAPON_FIRE_6',

'AS_WEAPON_RELOAD_1',
'AS_WEAPON_RELOAD_2',
'AS_WEAPON_RELOAD_3',
'AS_WEAPON_RELOAD_4',
'AS_WEAPON_RELOAD_5',
'AS_WEAPON_RELOAD_6',

'AS_WEAPON_SWITCH',

'AS_WPSTATE_IDLE',
'AS_WPSTATE_SWITCH',
'AS_WPSTATE_CHARGE',
'AS_WPSTATE_SPINUP',
'AS_WPSTATE_SPINDOWN',
'AS_WPSTATE_OVERHEAT',
'AS_WPSTATE_FIRE',
'AS_WPSTATE_BACKFIRE',

'AS_ITEM_SLEEP',
'AS_ITEM_ACTIVE',

'AS_CONSTRUCT_1',
'AS_CONSTRUCT_2',
'AS_CONSTRUCT_3',
'AS_CONSTRUCT_FINAL',

'AS_SUICIDE',

'AS_MINE2',
'AS_DEATH_SPECIAL');

